services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/redis:/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/core-engine
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASS: password
      POSTGRES_HOST: db
      REDIS_URL: redis://redis:6379/1