POSTGRES_HOST: localhost
POSTGRES_USER: postgres
POSTGRES_PASS: password

# to generate a new secret key, run `bin/rails db:encryption:init`
ENCRYPTION_PRIMARY_KEY:
ENCRYPTION_DETERMINISTIC_KEY:
ENCRYPTION_KEY_DERIVATION_SALT:

GMAIL_USERNAME:
GMAIL_PASSWORD:
GMAIL_DELIVERY_METHOD: 'test'

HOST: 'localhost:3000'

APPLICATION_NAME: 'Seventy Sete(Development)'

REDIS_URL: 'redis://localhost:6379/1'